### ISSUE TITLE
ts-install does not work against current nvim-treesitter

### ISSUE THREAD

**Issue by dsully** [lewis6991/ts-install.nvim#2]
Hi Lewis - I've been messing around with `ts-install.nvim` trying to figure out why it's not installing.

The first issue I've found is that returning the `nvim-treesitter.parsers` import will give an empty array.

If I change it as below, then things start moving along..

```diff
diff --git a/lua/ts-install/parsers.lua b/lua/ts-install/parsers.lua
index 61f2cdc6..cd6bbd38 100644
--- a/lua/ts-install/parsers.lua
+++ b/lua/ts-install/parsers.lua
@@ -35,7 +35,7 @@ local M = {}
 
 function M.get_parser_info()
   --- @type table<string,ts_install.ParserInfo>
-  return require('nvim-treesitter.parsers')
+  return require('nvim-treesitter.parsers').list
 end
 
 --- Get a list of all available parsers
```

However, the next issue occurs in `install.lua` : `M.get_package_path(...)`

```lua
local runtime_dirs = vim.api.nvim_get_runtime_file('runtime', true)
```

Returns an empty array, which means the `nvim-treesitter` path is never found, then:

```lua
if not nvim_treesitter_dir then
    error('nvim-treesitter is not installed')
end
```

Is called. I tried using `vim.api.nvim_list_runtime_paths()`, but that's not what the call to:

```lua
local queries_src = M.get_package_path('runtime', 'queries', lang)
```

Seems to want. Any thoughts here? Thanks

**Comment by lewis6991** [comment]
Just to double check. Are you using the `main` branch of nvim-treesitter?

**Comment by dsully** [comment]
I was not - that was the issue. Thanks!
